Article: On the estimation of average treatment effects with
right-censored time to event outcome and competing risks

Authors: Julien Péron, Maryam Idlhaj, Delphine Maucort-Boulch, Joris Giai, Pascal Roy, Laurence Collette, Marc Buyse, Brice Ozenne
Author responsible for writing the code: Brice Ozenne and Julien Péron.

E-mail of the author maintaining the code: brice.mh.ozenne@gmail.com

* Content of the folder
The infra structure of the empirical studies presented in the
manuscript is organized as follow:
- *the BATCH files* define the simulation studies. Each file was
  excecuted 20 times using a different id (obtain using
  =Sys.getenv("SGE_TASK_ID")= in R) and therefore a different seed
  when randomly generating the data. The output of the simulations
  were saved in a =results= directory, not uploaded on Github to save
  space but available upon request.  

- *the BUILD file* gather the results of the various simulations by
  reading the data in the =Results= directory, exports them in the
  =Results= directory. It also produces the figures and exports them
  in the =figures= directory.

- *the REVIEW file* contains additional analyses used to adress the
  comments of the reviewers. Results were exported in the directory
  =results-review= and figures in the directory =figures-review=.

